name: fsinander
favicon: null
layout_spectrum: 0.278427375247702
typography_spectrum: 0.13978529255837202
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.1388625679537654
  lightness: 0.5937577541917562
  saturation: 0.35069487406872213
  rhythmicContrast: 0.15362315671518445
purpose: []
